default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/flatiron_phase3_development

test:
  <<: *default
  database: db/flatiron_phase3_test

production:
  <<: *default
  database: db/flatiron_phase3_production
